Introduction to Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a.ndim, a.shape, a.dtype)

2 (2, 3) int64


In [6]:
np.ones((2,4))    #array of 1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.arange(100,112)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [9]:
A=np.ones((2,4))
B=np.zeros((3,4))

In [11]:
np.concatenate([A,B])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
C=np.ones((2,3,3))  #three dimensional array

In [13]:
C

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
np.random.random((10,3))

array([[0.7890215 , 0.68854485, 0.90693757],
       [0.91542675, 0.15807906, 0.04034129],
       [0.14394387, 0.0530313 , 0.67529802],
       [0.48313585, 0.11361472, 0.7583241 ],
       [0.55599168, 0.24154198, 0.71768254],
       [0.22551508, 0.29656983, 0.58340578],
       [0.33953448, 0.94131906, 0.41131814],
       [0.84913108, 0.89644121, 0.26908547],
       [0.40392981, 0.07643447, 0.32549538],
       [0.02329849, 0.72007845, 0.63418888]])

In [15]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [16]:
a=a.reshape(3,2)


In [17]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a[2,1]   #remember ython uses zero-indexing (start counting from zero)

6

In [19]:
a[1,1]

4

In [20]:
a[2,0]

5

In [21]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a=a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [23]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
a=np.arange(15).reshape(5,3)  #an example of method "chaining"
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
b=np.arange(15).reshape(5,2)

ValueError: cannot reshape array of size 15 into shape (5,2)

In [27]:
a=a.T
a

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [28]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [29]:
d=np.array([3,5,10])
d

array([ 3,  5, 10])

In [30]:
c*d

array([ 3, 10, 30])

In [31]:
a

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [32]:
a+10

array([[10, 13, 16, 19, 22],
       [11, 14, 17, 20, 23],
       [12, 15, 18, 21, 24]])

In [33]:
a>7

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False,  True,  True,  True]])

In [34]:
a

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [35]:
a.sum()

105

In [36]:
a.sum(axis=1)

array([30, 35, 40])

In [37]:
a.sum(axis=1, keepdims=True)

array([[30],
       [35],
       [40]])