# PRACTICE - NUMPY

### Complete the following questions. Add additional code cells as needed (recommended).

In [ ]:
import numpy as np

### Creating Arrays

In [ ]:
# QUESTION 1

# Create an 1d array from a list
# Print the array and its type
# Add 2 to each element of an array
# Explain the key difference between a list and an array
# What happens when you put an integer, a Boolean, and a string in the same array. Illustrate.



In [ ]:
# Create an 1d array from a list

In [15]:
my_list = [1, 2, 3, 4, 5]

# Create an 1d array from a list
my_array = np.array(my_list)

# Print the array and its type
print("Array:", my_array)
print("Type:", type(my_array))

# Add 2 to each element of an array
my_array += 2
print("Array after adding 2 to each element:", my_array)

# Key difference between a list and an array:
# The key difference between a list and an array is that a list can contain elements of different data types,
# while an array typically contains elements of the same data type.

# What happens when you put an integer, a Boolean, and a string in the same array:
mixed_array = np.array([1, True, "Hello"])
print("Array with mixed types:", mixed_array)



Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Array after adding 2 to each element: [3 4 5 6 7]
Array with mixed types: ['1' 'True' 'Hello']


In [ ]:
# QUESTION 2

# Create a 2d array from a list of lists
# Create a float 2d array
# Convert to 'int' datatype
# Convert to int then to str datatype
# # Create an object to hold numbers as well as strings
# If you want your array will hold characters and numbers in the same array, what will you set you datatype as...
# Convert an array back to a list



In [ ]:
# Create a 2d array from a list of lists
c=np.array([[1,2,3],[4,5,6]])
c

# Create a float 2d array
float_c = np.array(c, dtype=float)
float_c

# Convert to 'int' datatype
int_c = np.array(c, dtype=int)
int_c

# Convert to int then to str datatype
str_c = np.array(c, dtype=str)
str_c

# Create an object to hold numbers as well as strings
num_str = np.array([8, 9, 'Hello', 10, 'Name'])
num_str

# If you want your array will hold characters and numbers in the same array, what will you set you datatype as...

# Convert an array back to a list


### Inspecting size and shape

In [ ]:
# QUESTION 3

# Create a 2d array with 3 rows and 4 columns
# Print the shape of the array. Explain the output
# Print the size of the array. Explain the output
# Print the dimensions of the array. Explain the output.


### Extracting Items, Reversing Rows and adding Missing Values

In [ ]:
# QUESTION 4

# Using the array in Q3 extract the first 2 rows and columns
# Get a boolean output by applying the condition to each element.
# Reverse only the row positions
# Reverse the row and column positions
# Insert a nan and an inf in positions of your choosing
# # Replace nan and inf with -1.


### Creating a new array from existing array

In [ ]:
# QUESTION 5

# Explain the precautions you need to take when assigning a portion of an array to a new array. Illustrate with an example.
# What are some approaches you can take to keep the parent array intact? Illustrate with examples.


### Reshaping and Flattening

In [ ]:
# QUESTION 6

# Describe what is reshaping an array. Illustrate with an example.
# Describe what is flattening an array. Illustrate with an example.
# What are the two methods for flattening an array? Illustrate both methods with an example.
# What are the differences between these two methods.

In [16]:
a = np.array([1,2,3,4])
print(a)

#reshape
a_reshape = a.reshape(2,2)
print(a_reshape)  #reshapes the array by rows and columns specified, in this case converts it into 2d with 2 rows and 2 columns

#flattening 

a_flatten = a_reshape.flatten()
print(a_flatten) #flattens the array meaning converts it to 1d array i.e 1 row and 4 columns in this case

#flattening 2 methods
a_ravel = a_reshape.ravel()
print(a_ravel) #ravel returns a view, flatten always returns a copy, allocates new memory it is slower than ravel


[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


### Creating Sequences, repetitions and random numbers

In [1]:
# QUESTION 7


# Create an array with numbers 0 to 9
Q71 = np.arange(10)
print(Q71)

# Create an array 0 to 9 with step of 2
# Create an array 10 to 1, decreasing order
# Create an array with zeros or ones

'''
SIDENOTE: If you want to create an array of exactly 10 numbers between 1 and 50 you can use np.linspace.

np.linspace(start=1, stop=50, num=10, dtype=int)
array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

Note the dtype is forced as type int


To repeat an entire array n times use np.tile()
If you have an array assign to a variable a. To repeat the array twice ...np.tile(a, 2)

To repeat an element n times use np.repeat()
To repeat each element in the array a twice  ... np.repeat(a, 2))

'''

# Create an array using np.linspace()
# Repeat your array 4 times
# Repeat each element in the array 3 times


# Create an array with random numbers between [0,1) of shape 2,2
# Create an array with random integers between [0, 10) of shape 2,2

NameError: name 'np' is not defined

In [8]:
# Create an array with numbers 0 to 9
import numpy as np

Q71 = np.arange(10)
print(Q71)


[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Create an array 0 to 9 with step of 2
Q72 = np.arange(0,10,2)
print(Q72)

[0 2 4 6 8]


In [10]:
# Create an array 10 to 1, decreasing order
Q73 = np.arange(10, 0, -1)
print(Q73)


[10  9  8  7  6  5  4  3  2  1]


In [11]:
# Create an array with zeros or ones

Q74 = np.ones((5,5))
print(Q74)
Q742 = np.zeros((3,5))
print(Q742)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# Create an array using np.linspace()
Q75 = np.linspace(start=0, stop = 100, num= 20)
print(Q75)
Q751 = np.linspace(start=0, stop = 100, num= 20, dtype = int)
print(Q751)


[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
[  0   5  10  15  21  26  31  36  42  47  52  57  63  68  73  78  84  89
  94 100]


In [13]:
# Create an array with random numbers between [0,1) of shape 2,2
Q76 = np.random.random((2,2))
print(Q76)


[[0.53384653 0.44878145]
 [0.13838326 0.34326337]]


In [14]:
# Create an array with random integers between [0, 10) of shape 2,2

np.random.randint(0, 10, size=(2, 2))


array([[9, 6],
       [9, 6]])

### Use Case